-- MySQL Script generated by MySQL Workbench
-- mer. 20 juil. 2022 14:41:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lyrics-guesser
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lyrics-guesser
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lyrics-guesser` ;
USE `lyrics-guesser` ;

-- -----------------------------------------------------
-- Table `lyrics-guesser`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lyrics-guesser`.`theme` (
  `id` INT NOT NULL,
  `theme` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lyrics-guesser`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lyrics-guesser`.`theme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `theme` VARCHAR(255) NOT NULL,
  `img` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lyrics-guesser`.`song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lyrics-guesser`.`song` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `artist` VARCHAR(255) NOT NULL,
  `lyrics` TEXT(1000) NOT NULL,
  `img` VARCHAR(255) NULL,
  `link` VARCHAR(255) NULL,
  `theme_id` INT NOT NULL,
  PRIMARY KEY (`id`, `theme_id`),
  INDEX `fk_song_theme_idx` (`theme_id` ASC) VISIBLE,
  CONSTRAINT `fk_song_theme`
    FOREIGN KEY (`theme_id`)
    REFERENCES `lyrics-guesser`.`theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lyrics-guesser`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lyrics-guesser`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lyrics-guesser`.`user_has_theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lyrics-guesser`.`user_has_theme` (
  `highscore` INT NOT NULL,
  `user_id` INT NOT NULL,
  `theme_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `theme_id`),
  INDEX `fk_user_has_theme_theme1_idx` (`theme_id` ASC) VISIBLE,
  INDEX `fk_user_has_theme_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_theme_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `lyrics-guesser`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_theme_theme1`
    FOREIGN KEY (`theme_id`)
    REFERENCES `lyrics-guesser`.`theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'anas.mama' IDENTIFIED BY 'Y3ll0w**';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
